### ISSUE TITLE
Game fails to load resource packs and then crashes when i try to load a world in my modpack

### ISSUE THREAD

**Issue by thicccyniccy** [ellestuff/ellediscs#1]
As the title says, I know the ellediscs mod is causing the issue as when i take it out it works just fine, no clue what the problem is, help would be appreciated! Here is my list of mods and logs
![image](https://github.com/user-attachments/assets/76dfd311-085f-4662-b3ab-8d48060cd552)
![image](https://github.com/user-attachments/assets/1526d442-31f4-498d-97ba-cb125ce5cb07)

[Prism Launcher version: 8.0 (official)](https://mclo.gs/BamthCl)

**Comment by ellestuff** [comment]
Those are a lot of mods. Would it be possible for you to both send the crash log and the pack's .mrpack file so I can look into this further?
![image](https://github.com/user-attachments/assets/93d985be-d80f-4030-91f9-0f6794d64a4c)

**Comment by thicccyniccy** [comment]
Hey! thanks for the response, i’ll send both of those over as soon as i get home , i appreciate it

**Comment by thicccyniccy** [comment]
Alright, here is the mrpack file and the crashlog, thank you in advance
MRPACK: https://filebin.net/c9c90c26-d34a-461d-8bc2-0476fd913492/thiccyniccy_modpack.mrpack
Crash Log: https://mclo.gs/yzVH4bL

**Comment by ellestuff** [comment]
I've looked at the crash log and can see what the issue is and I will release a version that fixes it tomorrow as it is currently past 2am in my timezone.

**Comment by ellestuff** [comment]
I've just released an update for the mod on Modrinth, please try it and let me know if it works.
https://modrinth.com/mod/ellediscs/version/njRu33Bh

**Comment by thicccyniccy** [comment]
Will do so as soon as I get home

**Comment by thicccyniccy** [comment]
So i tested on my mac, same issue, maybe it will be different on my windows pc ill try when im home but it does the same thing on my mac so far even with version 1.0.2, still seems to be the same "silence" issue

Crash log: https://mclo.gs/ndVcknY

**Comment by ellestuff** [comment]
I've found the problem and will be releasing 1.0.3 later

**Comment by thicccyniccy** [comment]
Awesome, let me know when you release a fix please!

**Comment by ellestuff** [comment]
The bug should be fixed. In addition, I've added new disc types from the mod's experimental branch. If it's fixed please make sure to close the issue.
https://modrinth.com/mod/ellediscs/version/Ql5csfn0

**Comment by thicccyniccy** [comment]
Tested on my mac and it works like a charm! Amazing mod and thank you so much for your help!
